### ISSUE TITLE
Voting CPC Representatives from Projects

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/cross-project-council#152] opened 2019-04-08 19:57 UTC
Creating this issue to capture the appointments and nominees for the CPC per a question from one of our projects!

--- 

Impact Project Representative Appointments (up to 2 per project)
* Node: Matteo Collina (@mcollina ) & Joe Sepi (@joesepi) 
* [jQuery](https://github.com/jquery/jquery/issues/4344): Dave Methvin (@dmethvin) & Timmy Willison (@timmywil)
* Dojo: Matt Gadd ( @matt-gadd) & Dylan Schiemann (@dylans). 
* Appium: Jonah (@Jonahss) & Dan Graham (@dpgraham)
* webpack: Sean Larkin (@TheLarkInn) & Even Stensberg (@evenstensberg)

Growth & At Large Nominees (up to 2)
* Antón Molleda (@molant)
* Kris Borchers (@kborchers)
* Eemeli Aro (@eemeli)
* Chris Hiller (@boneskull)

**Comment by molant** [comment] 2019-04-08 20:30
webhint: @molant

**Comment by Jonahss** [comment] 2019-04-12 04:11
Appium representatives will be @dpgraham and myself 👋

**Comment by christian-bromann** [comment] 2019-04-12 08:55
As mentioned in webdriverio/webdriverio#3824 for WebdriverIO it will be TSC members of the project, depending who is available in US/Europe.

**Comment by kborchers** [comment] 2019-04-12 15:44
Architect's nominee is @kborchers per https://github.com/arc-repos/architect/issues/349

**Comment by knolleary** [comment] 2019-04-15 13:16
Node-RED's rep will be @knolleary (https://github.com/node-red/node-red/issues/2129)

**Comment by mhdawson** [comment] 2019-04-15 13:48
TSC progress on electing one Node.js rep, https://github.com/nodejs/TSC/issues/689 CommComm will kick off process as well.

**Comment by eemeli** [comment] 2019-04-16 06:31
Messageformat's nominee will be @eemeli (messageformat/messageformat#232).

**Comment by amiller-gh** [comment] 2019-04-17 17:01
CommComm nominations now open: https://github.com/nodejs/community-committee/issues/470

**Comment by mhdawson** [comment] 2019-04-25 19:11
@mcollina has been confirmed as the Node.js Voting CPC member.

**Comment by keywordnew** [comment] 2019-04-27 05:11
Thank you for taking on the work, @mcollina 🙏🏽

**Comment by keywordnew** [comment] 2019-04-27 05:15
CommComm will announce a CPC rep on 30th April. Progress is on nodejs/community-committee#470.

**Comment by dylans** [comment] 2019-05-01 14:48
For Dojo we would like to nominate Matt Gadd ( @matt-gadd) and me (Dylan Schiemann, @dylans). Let me know if that’s fine or if you have any questions.

**Comment by TheLarkInn** [comment] 2019-05-02 04:32
For webpack we nominate @thelarkinn Sean Larkin and @evenstensberg Even Stensberg as representatives.

**Comment by amiller-gh** [comment] 2019-05-02 13:52
Joe Sepi (@joesepi) has been elected the CommComm voting CPC member: https://github.com/nodejs/community-committee/issues/470

**Comment by jorydotcom** [comment] 2019-05-02 14:36
WOWOWOW way to go everyone, we got all our impact reps & nominees in right on schedule!!!!!!!!!!!!!
THANKYOU!!!!

**Comment by jorydotcom** [comment] 2019-05-02 14:42
follow-up ask to all reps & nominees - please take a sec and share your meeting time availability on [this spreadsheet](https://docs.google.com/spreadsheets/d/12e8lN9ywi-2kAtcW08WS3x3S-6TXiOO8_yxs3j0Sm2E/edit#gid=0) - note that there are 2 tabs!

**Comment by jorydotcom** [comment] 2019-05-06 19:00
Heads up, everyone who was selected or nominated to the CPC from an Impact, Growth, or At Large project has now been invited to join this repo for write access. Please check your notifications!

**Comment by brianwarner** [comment] 2019-05-08 14:53
@matt-gadd, @dpgraham, and @evenstensberg - I need your email addresses to populate the mailing list, please.  Can you drop me a line at bwarner@linuxfoundation.org?

**Comment by joesepi** [comment] 2019-05-08 18:57
In the most recent meeting, it was suggested and there was discussion around having all nominees from growth and at-large projects be voting members this first year to help bootstrap the council and further the work with more hands. (Rather than voting it down to only 2)

One thing I notice is that 3 of those 5 nominees are IBMers. If we were to invite all 5 of them to be voting members, that would make 4 out of 15 voting members IBMers (including me). The language states no more than 25% from one company. @boneskull said he would withdraw if this was an issue. I just want to share the situation for the group to discuss.

**Comment by boneskull** [comment] 2019-05-08 19:01
(4 of 15 is 26.66%)

**Comment by Jonahss** [comment] 2019-05-08 19:05
Thanks for pointing it out. I think one of them should drop out then.

**Comment by boneskull** [comment] 2019-05-08 23:02
or we could add another rep to make it 25% 😇

**Comment by MylesBorins** [comment] 2019-05-13 13:23
I'd like to +1 what @Jonahss suggested, one of the IBM members should drop out.

**Comment by mcollina** [comment] 2019-05-13 13:33
+1 to @Jonahss proposal

**Comment by joesepi** [comment] 2019-05-13 13:38
It was proposed last week--and discussed then as well as today's meeting--that we take on all growth and at-large nominees to bootstrap the CPC group for the first year and then next voting cycle elect 2 members from growth and at-large projects. There seems to be general consensus on this proposal.

The only issue is that that would put too many people from one company. We will work out that offline, one member from that company will withdraw, we will post an update on this thread soon with the withdrawn member. (some discussion above)

Beyond this one issue, we will assume consensus unless objections are noted here. Thanks!

**Comment by knolleary** [comment] 2019-05-14 16:09
Having discussed with @boneskull, I withdraw my nomination.

**Comment by MylesBorins** [comment] 2019-05-14 16:54
Thanks @knolleary 

With Nick withdrawing from the race we have our voting members! I've added everyone to the @openjs-foundation/cpc-voting-members team, which is a child team of @openjs-foundation/cpc

They have write access on this repo! Closing the issue

**Comment by joesepi** [comment] 2019-05-21 16:14
Hey y’all. I made a mistake. 

When I posted @eemeli in our IBM slack chat it was highlighted and when I looked at that users profile there were things that made me assume the IBMer and Eemeli were the same person. THEY ARE NOT. I should have checked this but I didn’t. 

Therefore, with the original intent being an inclination to have more voting members actively participating to “bootstrap” the first year of the CPC, I propose we allow @knolleary to be a voting member as well. 

Sorry for the mixup. :/

**Comment by boneskull** [comment] 2019-05-21 18:59
so we're clear, @eemeli, you don't work at IBM, right?

**Comment by eemeli** [comment] 2019-05-21 21:10
This is correct. I do not, and never have, worked for IBM. On the other hand, if this is the most indirect recruitment pitch I've received so far, please do get in touch with me we directly as well.

**Comment by MylesBorins** [comment] 2019-05-22 19:46
I went through and did my best to map folk to their affiliation

Node: Matteo Collina (@mcollina ) _NearForm_ & Joe Sepi (@joesepi) _IBM_ 
jQuery: Dave Methvin (@dmethvin) _Independent_ & Timmy Willison (@timmywil) _Pylon_
Dojo: Matt Gadd ( @matt-gadd) _Independent_ & Dylan Schiemann (@dylans). _SitePen_
Appium: Jonah (@Jonahss) _Cloud Grey_ & Dan Graham (@dpgraham) _Sauce Labs_
webpack: Sean Larkin (@TheLarkInn) _MSFT_ & Even Stensberg (@evenstensberg) _Independent_


Antón Molleda (@molant) _MSFT_
Kris Borchers (@kborchers) _MSFT_
Eemeli Aro (@eemeli) _Independent_
Chris Hiller (@boneskull) _IBM_
Nick O'Leary (@knolleary) _IBM_

Total: 15

Independent: 4
Microsoft: 3
IBM: 3
NearForm: 1
Pylon: 1
SitePen: 1
Cloud Grey: 1
Sauce Labs: 1

Did I get anything off?

**Comment by eemeli** [comment] 2019-05-23 09:37
If we're listing these associations anywhere, I'd appreciate myself as being listed under [Vincit](https://www.vincit.com/), as they do pay my salary and are sponsoring some of my work on messageformat.

**Comment by joesepi** [comment] 2019-05-30 10:26
This was briefly discussed in person at Collab Summit CPC meeting just now and there were multiple +1s and no objections to including @knolleary as a voting member. See above comments for more context.

**Closed by joesepi** 2019-05-30 10:26 UTC
Labels: cross-project-council-agenda

**Comment by dylans** [comment] 2019-05-31 01:55
Sorry for the very delayed reply... Matt Gadd is also with SitePen.
