### ISSUE TITLE
OpenJS Foundation Cross Project Council Meeting 2023-12-12

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/cross-project-council#1217] opened 2023-12-12 17:04 UTC
## Time

Sorry. Ad hoc issue created by hand.

## Links

* Minutes Google Doc: <https://docs.google.com/document/d/1ZNpp79QwmptgZZVlDphACdanqwuSxCGAP4-knuOM07E/edit>

## Agenda

Extracted from **cross-project-council-agenda** labelled issues and pull requests from the **openjs-foundation org** prior to the meeting.

### openjs-foundation/cross-project-council

https://github.com/openjs-foundation/cross-project-council/issues?q=is%3Aopen+is%3Aissue+label%3Across-project-council-agenda

## Invited

* OpenJS Foundation Cross Project Council
* OpenJS Foundation Project Maintainers
* OpenJS Foundation Board of Directors

## Notes

The agenda comes from issues labelled with `cross-project-council-agenda` across **all of the repositories in the openjs-foundation org**. Please label any additional issues that should be on the agenda before the meeting starts.

## Joining the meeting

link for participants: Zoom link: <https://zoom.us/j/920010234>

* For those who just want to watch: <https://livestream.openjsf.org>

---

**Invitees**

Please use the following emoji reactions in this post to indicate your
availability.

* :+1: - Attending
* :-1: - Not attending
* :confused: - Not sure yet

**Comment by ljharb** [comment] 2023-12-12 17:15
Duplicate of #1218, kind of.

**Closed by ljharb** 2023-12-12 17:15 UTC
