### ISSUE TITLE
Missing foundation mission and vision statements

### ISSUE THREAD

**Issue by tobie** [openjs-foundation/cross-project-council#322] opened 2019-09-14 13:01 UTC
[NEW_PROJECT_APPLICATION.md](https://github.com/openjs-foundation/cross-project-council/blob/master/NEW_PROJECT_APPLICATION.md) asks for a "statement of alignment with OpenJS Foundation charter and mission."

The [CPC charter](https://github.com/openjs-foundation/cross-project-council/blob/master/CPC-CHARTER.md)'s link to the foundation mission and vision is broken. I couldn't find anything that resembled a mission or vision statement either in the GitHub org or on the website besides a now closed issues (#7) related to the foundation merger.

I'd love a pointer to those statements if they exist somewhere and/or advice as how handle the requested info in NEW_PROJECT_APPLICATION.md.

Thanks!

**Comment by Eomm** [comment] 2019-09-17 16:26
I think it should refer to this one:
https://github.com/openjs-foundation/cross-project-council/blob/master/proposals/stage-3/EXPECTATIONS/EXPECTATIONS.md#mission-statement-drafts

But it is still in draft

**Comment by MylesBorins** [comment] 2019-09-17 18:37
Duplicate of https://github.com/openjs-foundation/cross-project-council/issues/230

@brianwarner @mkdolan I think this could be solved by having the bylaws somewhere we can point to. To we want them check into this repo or perhaps a repo specific to the bylaws?

**Comment by brianwarner** [comment] 2019-09-17 19:27
The bylaws are posted on the Foundation's website.  I just added a static link to them, so they'll always be easy to find: https://bylaws.openjsf.org

**Comment by jorydotcom** [comment] 2019-12-06 19:00
Closing as this was resolved by #406

**Closed by jorydotcom** 2019-12-06 19:00 UTC
Labels: documentation, duplicate
