### ISSUE TITLE
Community Fund budgeting

### ISSUE THREAD

**Issue by mcollina** [openjs-foundation/cross-project-council#1229] opened 2024-01-16 10:39 UTC
The board confirmed the 60k travel fund for 2024.

Based on https://github.com/openjs-foundation/standards/issues/256, the spending required for the Standards WG is around 22k. I think this work is _important_, so we should not cut down.

This leaves somewhat around 38k for Collaborator Summits and other events.
Node.js would likely 1 or 2 collaborator summits per year. How much should we allocate for those? Last year in Vancouver cost us around 12k both.

**Comment by ljharb** [comment] 2024-01-16 16:15
Should perhaps the remaining 38 be divided by impact and non-impact, and then we could look at those two groups separately? A “fair” split wouldn’t ofc be appropriate since not every non-standards expenditure is single-project-specific, but it’d probably help get a better ballpark idea of how much is reasonable for a project-specific expense to consume.

**Comment by tobie** [comment] 2024-02-24 22:21
Closing as duplicate of #1181

**Closed by tobie** 2024-02-24 22:21 UTC
Labels: TOPIC-travel-fund
