### ISSUE TITLE
Update CLA guidance to indicate project can just use ICLA

### ISSUE THREAD

**Issue by mhdawson** [openjs-foundation/cross-project-council#656] opened 2020-10-06 16:24 UTC
Need to update doc on OpenJS web site
Need to update existing IP guidance: https://github.com/openjs-foundation/cross-project-council/blob/master/IP_POLICY_GUIDANCE.md

**Comment by eemeli** [comment] 2020-10-07 06:57
Is this a dupe of #657?

**Comment by tobie** [comment] 2020-10-07 13:56
Yeah let's close this.

**Closed by tobie** 2020-10-07 13:56 UTC
Labels: duplicate
