### ISSUE TITLE
OpenJS Foundation Cross Project Council Meeting 2024-10-15

### ISSUE THREAD

**Issue by mhdawson** [openjs-foundation/cross-project-council#1376] opened 2024-10-14 13:05 UTC
## Time

**UTC Tue 15-Oct-2024 16:00 (04:00 PM)**:

| Timezone      | Date/Time             |
|---------------|-----------------------|
| US / Pacific  | Tue 15-Oct-2024 09:00 (09:00 AM) |
| US / Mountain | Tue 15-Oct-2024 10:00 (10:00 AM) |
| US / Central  | Tue 15-Oct-2024 11:00 (11:00 AM) |
| US / Eastern  | Tue 15-Oct-2024 12:00 (12:00 PM) |
| EU / Western  | Tue 15-Oct-2024 17:00 (05:00 PM) |
| EU / Central  | Tue 15-Oct-2024 18:00 (06:00 PM) |
| EU / Eastern  | Tue 15-Oct-2024 19:00 (07:00 PM) |
| Moscow        | Tue 15-Oct-2024 19:00 (07:00 PM) |
| Chennai       | Tue 15-Oct-2024 21:30 (09:30 PM) |
| Hangzhou      | Wed 16-Oct-2024 00:00 (12:00 AM) |
| Tokyo         | Wed 16-Oct-2024 01:00 (01:00 AM) |
| Sydney        | Wed 16-Oct-2024 03:00 (03:00 AM) |

Or in your local time:
* https://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Cross%20Project%20Council+Meeting+2024-10-15&iso=20241015T1600
* or https://www.wolframalpha.com/input/?i=04PM+UTC%2C+Oct+15%2C+2024+in+local+time

## Links

* Minutes Google Doc: <https://docs.google.com/document/d/1tMOJxSj57f_iKiEe6FERpHrwNe7-YXYstEaGXop1XWw/edit>

## Agenda

Extracted from **cross-project-council-agenda** labelled issues and pull requests from the **openjs-foundation org** prior to the meeting.

### openjs-foundation/cross-project-council

* Migrate project-status repo back here [#1374](https://github.com/openjs-foundation/cross-project-council/issues/1374)
* 2024 OpenJS Foundation CPC Selections:  Impact, At-Large, and Regular [#1370](https://github.com/openjs-foundation/cross-project-council/issues/1370)
* Create process docs to request infrastructure resources through OpenJSF partners [#1367](https://github.com/openjs-foundation/cross-project-council/issues/1367)
* Review `webpack`'s new governance model -- Impact project. [#1363](https://github.com/openjs-foundation/cross-project-council/issues/1363)
* The OpenJS CLAs should be updated [#1359](https://github.com/openjs-foundation/cross-project-council/issues/1359)
* Node.js is adopting an official Discord server for the Community - CoC review is needed [#1347](https://github.com/openjs-foundation/cross-project-council/issues/1347)
* Match repository structure to README Process and Policy section [#1345](https://github.com/openjs-foundation/cross-project-council/issues/1345)
* Document CoC Team selection process [#1297](https://github.com/openjs-foundation/cross-project-council/issues/1297)
* Code of Conduct Plan of Action [#1122](https://github.com/openjs-foundation/cross-project-council/issues/1122)
* IP Policy License Exemption Request - LoopBack [#885](https://github.com/openjs-foundation/cross-project-council/issues/885)

### openjs-foundation/project-status

* \[ONBOARDING\] Express [#15](https://github.com/openjs-foundation/project-status/issues/15)

### openjs-foundation/sustainability-collab-space

* OpenJS + Open Source Pledge [#12](https://github.com/openjs-foundation/sustainability-collab-space/issues/12)

## Invited

* OpenJS Foundation Cross Project Council
* OpenJS Foundation Project Maintainers
* OpenJS Foundation Board of Directors

## Notes

The agenda comes from issues labelled with `cross-project-council-agenda` across **all of the repositories in the openjs-foundation org**. Please label any additional issues that should be on the agenda before the meeting starts.

## Joining the meeting

link for participants: Please refer to the <a href=https://calendar.openjsf.org>OpenJS public calendar</a> for meeting link

* For those who just want to watch: <https://livestream.openjsf.org>

---

**Invitees**

Please use the following emoji reactions in this post to indicate your
availability.

* :+1: - Attending
* :-1: - Not attending
* :confused: - Not sure yet

**Comment by ljharb** [comment] 2024-10-14 14:14
Duplicate of #1375

**Closed by ljharb** 2024-10-14 14:14 UTC
Labels: cpc-meeting
