### ISSUE TITLE
Collaborator Summit at Node+JS Interactive / new repo

### ISSUE THREAD

**Issue by mcollina** [openjs-foundation/cross-project-council#242] opened 2019-06-28 08:37 UTC
I propose we create a new repo for the Collaborator Summit under the OpenJS Foundation github organization. Alternatively, we could move the https://github.com/nodejs/summit one here. What do you think? What would be the best approach?

There are still some questions to move https://github.com/openjs-foundation/cross-project-council/tree/master/proposals/stage-1/COLLAB_SUMMIT to stage 3, but we need to start the organization of the new summit, kick off a team, and figure out all the agenda and topics.

**Comment by eemeli** [comment] 2019-06-28 17:41
I'd prefer/recommend moving `nodejs/summit` here. It's obvious that that's the origin of the OpenJS summit, and that that's a community that we would like to keep with us.

**Comment by mhdawson** [comment] 2019-06-28 18:54
I'm ok with moving it here but we should get Node.js TSC and commcomm's ok first.

**Comment by MylesBorins** [comment] 2019-07-02 16:57
is this a dupe of https://github.com/openjs-foundation/cross-project-council/issues/208?

**Comment by keywordnew** [comment] 2019-07-09 04:25
Seems like a convergent conversation with #208. This is about making a new repo or bringing nodejs/summit. #208 is about the next Summit and is also touching on the repo status.

I'm ok with moving the repo to OpenJS, pending TSC and CommComm +1. If there are objections, I can open an issue in admin to move forward.

**Comment by mhdawson** [comment] 2019-07-09 13:43
I think the next step is to open an issue in the admin repo with the suggestion to move the repo from the Node.js org to the OpenJS Org and tagged for the CommComm and TSC agendas.  Would probably be best if the issue was opened by the Node.js CTC reps.  @joesepi would you be able to open the issue and managed the conversation on the CommComm side?  I know that @mcollina  is busy right now so I can manage the conversation on the TSC side.

**Comment by keywordnew** [comment] 2019-08-13 18:29
Created [#403](https://github.com/nodejs/admin/issues/403) in `nodejs/admin` as a next step to keep things moving.

**Comment by mhdawson** [comment] 2019-08-29 21:35
@keywordnew I moved the repo over but I'm not an org owner in the openjs-foundation so I can't update members/team.

@openjs-foundation/cpc-voting-members
can one of the voting members help out with this?

**Comment by keywordnew** [comment] 2019-08-30 02:06
- [x] Repo moved.
- [x] Team created.

Thanks for all the help folks! 💯

I'm going to close this issue. Please feel free to reopen this issue if necessary, or open a new issue at the new location: https://github.com/openjs-foundation/summit

**Closed by keywordnew** 2019-08-30 02:06 UTC
Labels: cross-project-council-agenda
